# Site settings
title: yeooo.delivery
tagline: delivery and collections in Northern Ireland.
description: Who is delivering in Northern Ireland and what services are offering click and collection.
url: https://yeooo.delivery
author: David Shawe
twitter:
  username: yeoooDelivery
  card: summary


# Build settings
permalink: :title/
sass:
  sass_dir: css

plugins:
  - pagemaster
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  services:
    output: true
    source: deliveryServices.csv
    id_key: name
    layout: page
  locations:
    output: true
    source: deliveryServiceLocation.csv
    id_key: location
    layout: location

