# Site settings
title: Yeooo Delivery
shortTitle: yeooo
description: Find out where you can order and get deliveries in and around Northern Ireland
url: https://yeooo.delivery


# Build settings
permalink: :title/
sass:
  sass_dir: css

plugins:
  - pagemaster
  - jekyll-sitemap

collections:
  services:
    output: true
    source: deliveryServices.csv
    id_key: name
    layout: page

